version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT_UI_WEB}:${PORT_UI_DOCKER}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net
volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: ${BACK_SUBNET}
  front_net:
    ipam:
      driver: default
      config:
        - subnet: ${FRONT_SUBNET}
